select
	H.CREATORID,
	U.FAMILYNAME || U.FIRSTNAME as CREATORNAME,
	H.STARTDATE,
	H.ENDDATE,
	D.SHORTNAME as DivisionShortName,
	H.REASON
from
	HOLIDAYS as H
	left join USERS as U
		on H.CREATORID = U.ACOUNT
	left join HOLIDAYDIVISIONS as D
		on H.DIVISIONID = D.DIVISIONID
where
	H.CREATORID = ?
	and ? <= H.STARTDATE
	and H.ENDDATE <= ?

